<a href="https://colab.research.google.com/github/tannyyaawadhwani-design/puthony/blob/main/day2py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)

# Shape & Dimensions
print("Shape:", arr1.shape)
print("Dimension:", arr1.ndim)

# Array operations
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Standard Deviation:", np.std(arr1))


arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Number of Dimensions:", arr2.ndim)

# Access elements
print("First row:", arr2[0])
print("Element at row1,col2:", arr2[0,1])


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise operations
print("Add:", a+b )
print("Multiply:", a * b)
print("Subtract:", b - a)

# Scalar operations
print("Multiply by 2:", a * 2)

# Create sequences
print("arange:", np.arange(0, 10, 2))  # start, stop, step
print("linspace:", np.linspace(0, 1, 5))  # start, stop, num_points

# Random numbers
print("Random integers:", np.random.randint(1, 10, 5))
print("Random floats:", np.random.rand(3))




#mini exercise
import numpy as np
kharcha= np.array([300,20,170,211,124,853,210,395,253,81])
print("kaha udayi 10 din:",kharcha)
print("pura total kharch:",np.sum(kharcha))
print("average kitna:", np.mean(kharcha))
print("sabse jada:", np.max(kharcha))
print("sabse kam:", np.min(kharcha))
kharcha2D= kharcha.reshape(2,5)
print("2D:",kharcha2D)
print("sumrow1:", np.sum(kharcha2D[0]))
print("sumrow2:", np.sum(kharcha2D[1]))
print("sum of rows:",np.sum(kharcha2D, axis=1))
# Row-wise average
print("Row-wise averages:",  np.mean(kharcha2D,axis=1))
# Column-wise sum
print("Column-wise sums:",np.sum(kharcha2D, axis=0))

import numpy as np

arr = np.array([1,2,3,4,5])
print("Square:", np.square(arr))
print("Square root:", np.sqrt(arr))
print("Greater than 3:", arr > 3)

arr2D = np.array([[10,20,30],[40,50,60]])
print(arr2D[0, 1:3])  # [20 30]
print(arr2D[0:3])

arr = np.array([10, 25, 30, 45])
print(arr[arr > 20])  # [25 30 45]
print(arr>20)

arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D.flatten())   # [1 2 3 4 5 6]
print(arr2D.T)           # Transposed 2D array


#mini exercise
randint= np.random.randint(0,50,12)
print("random array:", randint)
randit= randint.reshape(3,4)
print("3*4 random array:",randint.reshape(3,4))
#since printing elements above 20 asked
print("above 20:",randit[randit>20])
print("row-wise sum and column-wise average:", np.sum(randit, axis=0) , np.mean(randit, axis=1))
print( "flattened array:",randit.flatten())
print("only odd number:", randit[randit%2!=0])


Array: [1 2 3 4 5]
Shape: (5,)
Dimension: 1
Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimensions: 2
First row: [1 2 3]
Element at row1,col2: 2
Add: [5 7 9]
Multiply: [ 4 10 18]
Subtract: [3 3 3]
Multiply by 2: [2 4 6]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]
Random integers: [8 2 8 4 5]
Random floats: [0.83383852 0.72915159 0.43307071]
kaha udayi 10 din: [300  20 170 211 124 853 210 395 253  81]
pura total kharch: 2617
average kitna: 261.7
sabse jada: 853
sabse kam: 20
2D: [[300  20 170 211 124]
 [853 210 395 253  81]]
sumrow1: 825
sumrow2: 1792
sum of rows: [ 825 1792]
Row-wise averages: [165.  358.4]
Column-wise sums: [1153  230  565  464  205]
Square: [ 1  4  9 16 25]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Greater than 3: [False False False  True  True]
[20 30]
[[10 20 30]
 [40 50 60]]
[25 30 45]
[False  True  True  True]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
random arra